sudo: false
notifications:
  email: false
language: python
matrix:
  include:
    - python: 3.6
      env: TOX_ENV=py36
    - python: 3.6
      env: TOX_ENV=coveralls
install:
  - pip install tox
script:
  - tox -e $TOX_ENV
