sudo: true #required to use docker
notifications:
  email: false
language: python
python:
  - "3.6"
env:
  - TOX_ENV=py36
  - TOX_ENV=coveralls
  - TOX_ENV=flake8
services:
  - docker
install:
  - pip install tox
script:
  - tox -e $TOX_ENV
jobs:
  include:
    - stage: ECR deploy
      install:
        - pip install pipenv awscli
      script: skip
      before_deploy: make dist
      #deploy:
      #  skip_cleanup: true
      #  provider: s3
      #  access_key_id: $AWS_ACCESS_KEY_ID
      #  secret_access_key: $AWS_SECRET_ACCESS_KEY
      #  bucket: "carbon-deploy"
      #  local_dir: "dist-aws"
      #after_deploy: bash publish.sh
