### This is the Terraform-generated dev-build.yml workflow for the carbon-dev app repository ###
name: Dev Build and Deploy Fargate Container
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths-ignore:
      - '.github/**'

jobs:
  deploy:
    name: Dev Deploy Fargate Container
    uses: mitlibraries/.github/.github/workflows/fargate-shared-deploy-dev.yml@carbon-reqs
    secrets: inherit
    with:
      AWS_REGION: "us-east-1"
      GHA_ROLE: "carbon-gha-dev"
      ECR: "carbon-dev"
      DEPS: "make deps; make wheel"
